#!/usr/bin/ruby
require 'autotest'
require 'autotest/redgreen'
# require 'autotest/timestamp'

module Autotest::Growl
  def self.growl title, msg, img, pri=0, stick=""
    system "growlnotify -n autotest --image #{img} -p #{pri} -m #{msg.inspect} #{title} #{stick}"
  end

  Autotest.add_hook :ran_command do |at|
    unless at.results.last.nil?
      output = (at.results.last.gsub(/\e\[\d+m/,'')).gsub(/\n/,'')
      if /[1-9] failure/.match(output)
        growl "Fail", "#{output}", '~/dotfiles/autotest_images/rails_fail.png', 2 #, "-s"
      else
        growl "Pass", "#{output}", '~/dotfiles/autotest_images/rails_pass.png', 2
      end
    end
  end
end
