#!/bin/bash

alias l='ls -lahG'
alias ll='ls -lGarth'
alias ..='cd ..'
alias ...='cd ../..'
alias less='less -rf'

HISTFILESIZE=3000
export PATH=~/bin:~/packages/bin:/opt/local/lib/mysql5/bin:/opt/local/bin:/usr/local/apache2/bin:$PATH
export LSCOLORS="ExfxcxdxBxegedabagacad"
export MANPATH="/usr/local/man:$MANPATH"
export EDITOR="vim"
export HISTSIZE=5000

function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/.\1/'
}

PS1="[\t]\e[1;34m[\u@\e[1;32m\h\e[m:\w\e[1;32m\$(parse_git_branch)\e[m]\\$"

bind '"\e[5~"':history-search-backward
bind '"\e[6~"':history-search-forward

# enable bash completion in interactive shells
if [ -f /opt/local/etc/bash_completion ]; then
  . /opt/local/etc/bash_completion
fi

complete -C ~/dotfiles/scripts/rake_autocomplete.txt -o default rake

#########
# rails #
#########

alias ss='script/server'
alias sc='script/console'

################################################
# add host specific commands to ~/.bash_extras #
################################################

if [ -f ~/.bash_extras ]; then
  source ~/.bash_extras
fi
