#!/bin/bash

alias l='ls -lahG'
alias ll='ls -lGarth'
alias ..='cd ..'
alias ...='cd ../..'
alias less='less -rf'

if [[ `uname` == 'Linux' ]]; then
  alias l='ls -lah --color'
  alias ll='ls -larth --color'
  alias mvim='gvim'
  alias gitx='gitg'
fi

HISTFILESIZE=3000
# export PATH=~/packages/R13B04/bin:~/packages/erlang/bin:~/dotfiles/scripts/:~/bin:~/packages/bin:/usr/local/mysql/bin:/usr/local/apache2/bin:/usr/local/bin:/usr/sbin:$PATH
export PATH=~/dotfiles/scripts/:~/bin:~/packages/bin:/usr/local/mysql/bin:/usr/local/apache2/bin:/usr/local/bin:/usr/sbin:$PATH
export PATH=~/.bundle/ruby/1.8/bin/:$PATH
export PATH=/usr/local/share/python:$PATH
export LSCOLORS="ExfxcxdxBxegedabagacad"
export MANPATH=~/packages/man:/usr/local/man:$MANPATH
export EDITOR="vim"
export HISTSIZE=5000

# Go
export GOROOT=$HOME/go
export GOARCH=amd64
export GOOS=darwin

# Git
source ~/Dropbox/dotfiles/scripts/git-completion.bash

function set_prompt {
  local BLUE="\[\033[1;34m\]"
  local GREEN="\[\033[1;32m\]"
  local RESET="\[\033[1;37m\]"
  local USERNAME="\u"
  local HOST="\h"
  #local GIT= __git_ps1(".%s")

  # prompt1="[\t] ${BLUE}${USERNAME}${RESET}@${GREEN}${HOST}${RESET}:\w${GREEN}"
  prompt1="${BLUE}${USERNAME}${RESET}@${GREEN}${HOST}${RESET}:\w${GREEN}"
  prompt2='$(__git_ps1 ".%s")'
  prompt3="${RESET}"

  PS1="$prompt1$prompt2$prompt3$ "

}

set_prompt
#PS1='[\t]\e[1;34m[\u@\e[1;32m\h\e[m:\w\e[1;32m$(__git_ps1 ".%s")\e[m]\\$'

bind '"\e[5~"':history-search-backward
bind '"\e[6~"':history-search-forward

# enable bash completion in interactive shells
if [ -f /opt/local/etc/bash_completion ]; then
  . /opt/local/etc/bash_completion
fi

if [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi

# Rake auto-complete
complete -C ~/dotfiles/scripts/rake_autocomplete.txt -o default rake

# TEMP=`which cheat`
# if [ $? == 0 ]; then
#   # Cache, and complete, Cheats
#   if [ ! -r ~/.cheats ] || [[ ! "" == `find ~ '.cheats' -ctime 1 -maxdepth 0` ]]; then
#     echo "Rebuilding Cheat cache... "
#     cheat sheets | egrep '^ ' | awk {'print $1'} > ~/.cheats
#   fi
#   complete -W "$(cat ~/.cheats)" cheat
# fi

#########
# rails #
#########

alias ss='script/server'
alias sc='script/console'
alias sd='script/dbconsole'

################################################
# add host specific commands to ~/.bash_extras #
################################################

if [ -f ~/.bash_extras ]; then
  source ~/.bash_extras
fi
if [ -f `brew --prefix`/Library/Contributions/brew_bash_completion.sh ]; then
    source `brew --prefix`/Library/Contributions/brew_bash_completion.sh
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session.

export ARCHFLAGS="-arch x86_64"

ulimit -n 2560
