set nocompatible          " We're running Vim, not Vi!
syntax on                 " Enable syntax highlighting
filetype plugin indent on " Enable filetype-specific indenting and plugins

set autoread
set number
set smartindent
set nobackup
set incsearch
set hlsearch
set wrapscan
set smartcase ignorecase
set showcmd
set scrolloff=5
set laststatus=2
set statusline=%F%m\ %y\ l:\%l\/%L\ \%p%%\ c:\%c
set expandtab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set listchars=tab:>-,eol:$
set guioptions=egmrLt
let mapleader = ","

" --- Backups & Files ---
set backup                 " Enable creation of backup file.
set backupdir=~/.vim/backups " Where backups will go.
set directory=~/.vim/tmp     " Where temporary files will go.

colorscheme vividchalk
highlight comment ctermfg=darkgreen
hi Cursor guifg=#000000 guibg=#888888

autocmd BufRead *.ru set filetype=ruby
autocmd BufRead *.feature set filetype=ruby
autocmd BufNewFile,BufRead COMMIT_EDITMSG set filetype=gitcommit
autocmd BufNewFile,BufRead *.textile setf textile

runtime! macros/matchit.vim


" --- mappings ---
map <Leader>b :BufExplorer<CR>
map <Leader>f :Find<space>
map <Leader>n :NERDTree<CR>

" --- Window control ---
map <silent> <unique> + <C-w>+
map <silent> <unique> - <C-w>-

" --- Erlang ---
map <Leader>gf :0r ~/.vim/templates/gen_server_template.full<CR>:set filetype=erlang<CR>
map <Leader>gm :0r ~/.vim/templates/gen_server_template.mini<CR>:set filetype=erlang<CR>

" --- Rails ---
imap <C-l> <Space>=><Space>

" --- Rspec ---
map <Leader>ofs :%s/ it / xit <CR>''?xit<CR>x:w<CR>
map <Leader>ons :%s/ xit / it /<CR>'':w<CR>

" --- Align ---

" From inside a hash, autoindents, then aligns on =>
nmap <silent> <Leader>ih <ESC>:AlignPush<CR>:AlignCtrl lp1P1l<CR>mmviB:Align =><CR>:AlignPop<CR>'mvaB=

" Autoformats a single line hash
nmap <Leader>fh <ESC>^:s/{/{\r/<CR>:s/}$/\r}<CR>vaB:s/\v,\s*:/,\r:/g<CR><Leader>ih

" Aligns visual block on =
vmap <silent> <Leader>i= <ESC>:AlignPush<CR>:AlignCtrl lp1P1l<CR>:'<,'>Align =<CR>:AlignPop<CR>

" Aligns visual block on ,
vmap <silent> <Leader>i, <ESC>:AlignPush<CR>:AlignCtrl lp0P1l<CR>:'<,'>Align ,<CR>:AlignPop<CR>

" Aligns visual block on (
vmap <silent> <Leader>i( <ESC>:AlignPush<CR>:AlignCtrl lp0P0l<CR>:'<,'>Align (<CR>:AlignPop<CR>
